Page({
    data:{
        lession_list:[
            {
                date:'2018/07/02',
                weekday:'周一',
                weekday_index:1,
                items:[
                    {
                        time:'08:00~11:00',
                        subject:'趣味数学',
                        teacher:"田雨"
                    },
                    {
                        time:'08:00~12:00',
                        subject:'趣味数学2',
                        teacher:"田雨2"
                    }
                ]
            },
            {
                date:'2018/07/03',
                weekday:'周二',
                weekday_index:2,
                items:[
                    {
                        time:'08:00~11:00',
                        subject:'趣味数学',
                        teacher:"田雨"
                    }
                ]
            },
            {
                date:'2018/07/04',
                weekday:'周三',
                weekday_index:3,
                items:[
                    {
                        time:'08:00~11:00',
                        subject:'趣味数学',
                        teacher:"田雨"
                    },
                    {
                        time:'08:00~12:00',
                        subject:'趣味数学2',
                        teacher:"田雨2"
                    },
                    {
                        time:'08:00~11:00',
                        subject:'趣味数学',
                        teacher:"田雨"
                    },
                ]
            },
            {
                date:'2018/07/02',
                weekday:'周四',
                weekday_index:4,
                items:[
                    {
                        time:'08:00~11:00',
                        subject:'趣味数学',
                        teacher:"田雨"
                    },
                    {
                        time:'08:00~12:00',
                        subject:'趣味数学2',
                        teacher:"田雨2"
                    }
                ]
            },
            {
                date:'2018/07/02',
                weekday:'周五',
                weekday_index:5,
                items:[
                    {
                        time:'08:00~11:00',
                        subject:'趣味数学',
                        teacher:"田雨"
                    },
                    {
                        time:'08:00~12:00',
                        subject:'趣味数学2',
                        teacher:"田雨2"
                    }
                ]
            },
            {
                date:'2018/07/02',
                weekday:'周六',
                weekday_index:6,
                items:[
                    {
                        time:'08:00~11:00',
                        subject:'趣味数学',
                        teacher:"田雨"
                    },
                    {
                        time:'08:00~12:00',
                        subject:'趣味数学2',
                        teacher:"田雨2"
                    }
                ]
            },
            {
                date:'2018/07/02',
                weekday:'周日',
                weekday_index:7,
                items:[
                    {
                        time:'08:00~11:00',
                        subject:'趣味数学',
                        teacher:"田雨"
                    },
                    {
                        time:'08:00~12:00',
                        subject:'趣味数学2',
                        teacher:"田雨2"
                    }
                ]
            }
        ]
    },
    
});