var app_version = 'v3.2.5';

 var base_url = 'https://api.yixsu.com/index.php';
 var base_url_h5 = 'https://api.yixsu.com';
// var base_url = 'http://www.myweb.com/git-res/earth_php/index.php';
// var base_url_h5 = 'http://www.myweb.com/git-res/earth_php';
// var base_url = 'https://api.88plus.net/index.php';
// var base_url_h5 = 'https://api.88plus.net';
var urls = {
    login:base_url+'/wenyuanjiaoyu/auth/login',
    userinfo:base_url+'/wenyuanjiaoyu/users/info',
    send_code:base_url+'/waibao/common/send_code_wenyuan',
    verify_code:base_url+'/waibao/common/verify_code_wenyuan',
    bind_tel:base_url+'/wenyuanjiaoyu/users/bind_tel',
    news_list:base_url+'/wenyuanjiaoyu/news/index',
    bind_student:base_url+'/wenyuanjiaoyu/student/bind_student',
    get_bind_students:base_url+'/wenyuanjiaoyu/student/get_bind_students',
    change_avatar:base_url+'/wenyuanjiaoyu/student/change_avatar',
    upload:base_url+'/waibao/common/qiniu_upload',
    pay_create:base_url+'/wenyuanjiaoyu/pay/wechat_pay_create',
    pay_create_video:base_url+'/wenyuanjiaoyu/pay/wechat_pay_create_video',
    pay_create_course_order:base_url+'/wenyuanjiaoyu/pay/wechat_pay_create_course_order',
    pay_create_sign_course_order:base_url+'/wenyuanjiaoyu/pay/wechat_pay_create_sign_course_order',
    change_active_student:base_url+'/wenyuanjiaoyu/student/change_active_student',
    get_student_class_info:base_url+'/wenyuanjiaoyu/student/get_student_class_info',
    get_current_student:base_url+'/wenyuanjiaoyu/student/get_current_student',
    get_lession_time_list:base_url+'/wenyuanjiaoyu/student/get_lession_time_list',
    get_student_examinations:base_url+'/wenyuanjiaoyu/examination/get_student_examinations',
    get_examination_detail:base_url+'/wenyuanjiaoyu/examination/get_examination_detail',
    examination_sign:base_url+'/wenyuanjiaoyu/examination_signs/edit',
    examination_signs_draft:base_url+'/wenyuanjiaoyu/examination_signs/sign_draft',
    check_pay_status:base_url+'/wenyuanjiaoyu/examination_signs/check_pay_status',
    edit_avatar:base_url+'/wenyuanjiaoyu/examination_signs/edit_avatar',
    get_current_student_examine_log:base_url+'/wenyuanjiaoyu/examination/get_current_student_examine_log',
    suggest_edit:base_url+'/wenyuanjiaoyu/suggest/edit',
    get_my_words:base_url+'/wenyuanjiaoyu/words/get_my_words',
    course_list:base_url+'/wenyuanjiaoyu/goods/index',
    get_goods_detail:base_url+'/wenyuanjiaoyu/goods/info',
    goods_comment_list:base_url+'/wenyuanjiaoyu/goods_comment/index',
    add_order:base_url+'/wenyuanjiaoyu/order/edit',
    add_order_sign_course:base_url+'/wenyuanjiaoyu/order/add_order_sign_course',
    get_order_detail:base_url+'/wenyuanjiaoyu/order/info',
    cancel_order:base_url+'/wenyuanjiaoyu/order/cancel',
    cancel_sign_course:base_url+'/wenyuanjiaoyu/order/cancel_sign_course',
    my_order_list:base_url+'/wenyuanjiaoyu/order/my_order_list',
    comment_goods:base_url+'/wenyuanjiaoyu/goods/comment_goods',
    get_sign_course_student_list:base_url+'/wenyuanjiaoyu/student/get_sign_course_student_list',
    get_sign_class_list:base_url+'/wenyuanjiaoyu/sign_course/get_sign_class_list',
    get_class_info:base_url+'/wenyuanjiaoyu/sign_course/get_class_info',
    get_sign_course_stage:base_url+'/wenyuanjiaoyu/sign_stage/get_active_one',
    stage_info:base_url+'/wenyuanjiaoyu/sign_stage/info',
    user_notice_agreement_list:base_url+'/wenyuanjiaoyu/user_notice_agreement/get_all',
    user_notice_agreement_edit:base_url+'/wenyuanjiaoyu/user_notice_agreement/edit',
    user_notice_agreement_info:base_url+'/wenyuanjiaoyu/user_notice_agreement/info',
    check_can_open_ticket:base_url+'/wenyuanjiaoyu/examination_signs/check_can_open_ticket',
    quit_queue:base_url+'/wenyuanjiaoyu/order/quit_queue',
    cancel_pay:base_url+'/wenyuanjiaoyu/pay/cancel_pay',
    homework_class_list:base_url+'/wenyuanjiaoyu/student/homework_class_list',
    class_homework_list:base_url+'/wenyuanjiaoyu/homework_class/index',
    my_home_work_detail:base_url+'/wenyuanjiaoyu/homework_class/my_home_work_detail',
    homework_upload_docs:base_url+'/wenyuanjiaoyu/student_homework_result/upload_docs',
    submit_result:base_url+'/wenyuanjiaoyu/question_student_result/submit_result',
    reckon_result:base_url+'/wenyuanjiaoyu/student_homework_result/reckon_result',
    gen_homework_result_share:base_url+'/wenyuanjiaoyu/homework_class/gen_homework_result_share',
    video_list:base_url+'/wenyuanjiaoyu/video/list_front',
    video_url:base_url+'/wenyuanjiaoyu/video/video_url',
    user_video_collect:base_url+'/wenyuanjiaoyu/user_video_collect/collect',
}

module.exports = {
    base_url:base_url,
    base_url_h5:base_url_h5,
    urls: urls,
    app_version:app_version
}
